"""Markdown report generator."""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

from src.config import Config
from src.utils.logger import get_logger


class MarkdownGenerator:
    """Generator for Markdown research reports."""

    def __init__(self):
        """Initialize Markdown generator."""
        self.logger = get_logger(self.__class__.__name__)

    def generate_report(
        self,
        topic: str,
        analysis_result: Dict[str, Any],
        sources: Dict[str, List[Dict[str, str]]],
        output_path: Path
    ) -> bool:
        """
        Generate a comprehensive Markdown research report.

        Args:
            topic: Research topic
            analysis_result: Analysis results from Claude
            sources: Organized data sources
            output_path: Path to save the report

        Returns:
            True if successful, False otherwise
        """
        self.logger.info("📝 Generating Markdown report...")

        try:
            # Build report content
            report_content = self._build_report(topic, analysis_result, sources)

            # Ensure output directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Write to file
            output_path.write_text(report_content, encoding="utf-8")

            self.logger.info(f"✅ Report saved to: {output_path}")
            return True

        except Exception as e:
            self.logger.error(f"❌ Error generating report: {e}")
            return False

    def _build_report(
        self,
        topic: str,
        analysis_result: Dict[str, Any],
        sources: Dict[str, List[Dict[str, str]]]
    ) -> str:
        """
        Build the complete report content.

        Args:
            topic: Research topic
            analysis_result: Analysis results
            sources: Organized sources

        Returns:
            Complete report content as string
        """
        now = datetime.now()
        timestamp = now.strftime("%Y-%m-%d %H:%M:%S")

        # Count sources
        x_count = len(sources.get("x", []))
        web_count = len(sources.get("web", []))
        total_sources = x_count + web_count

        # Get metadata
        metadata = analysis_result.get("metadata", {})
        model = metadata.get("model", "Claude Sonnet 4")
        tokens_used = metadata.get("tokens_used", "N/A")

        # Build report sections
        sections = []

        # Header
        sections.append(f"# {topic} - Research Report\n")
        sections.append(f"**Generated**: {timestamp}  ")
        sections.append(f"**Data Sources**: X ({x_count}), Web ({web_count}) - Total: {total_sources}  ")
        sections.append(f"**Analysis Model**: {model}  ")
        sections.append(f"**Tokens Used**: {tokens_used}  ")
        sections.append("\n---\n")

        # Analysis content from Claude
        analysis_text = analysis_result.get("analysis", "")
        if analysis_text:
            sections.append(analysis_text)
            sections.append("\n---\n")

        # Data sources section
        sections.append("\n## 📚 Data Sources\n")

        # X sources
        if x_count > 0:
            sections.append(f"\n### X (Twitter) - {x_count} posts\n")
            for i, item in enumerate(sources["x"], 1):
                author = item.get("author", "Unknown")
                content = item.get("content", "")
                date = item.get("date", "")
                url = item.get("url", "")
                engagement = item.get("engagement", {})
                likes = engagement.get("likes", 0)

                sections.append(f"{i}. **@{author}** - {date}  ")
                sections.append(f"   {content}  ")
                sections.append(f"   👍 {likes} likes | [View Tweet]({url})  \n")

        # Web sources
        if web_count > 0:
            sections.append(f"\n### Web - {web_count} results\n")
            for i, item in enumerate(sources["web"], 1):
                title = item.get("title", "Untitled")
                source = item.get("source", "Unknown")
                date = item.get("date", "")
                url = item.get("url", "")

                sections.append(f"{i}. **{title}**  ")
                sections.append(f"   Source: {source} | Date: {date}  ")
                sections.append(f"   [Read Article]({url})  \n")

        # Footer
        sections.append("\n---\n")
        sections.append("\n*This report was generated by Research Agent - AI-powered research automation tool*\n")

        return "\n".join(sections)

    def generate_filename(self, topic: str) -> str:
        """
        Generate a filename for the report.

        Args:
            topic: Research topic

        Returns:
            Filename string
        """
        # Sanitize topic for filename
        safe_topic = "".join(c if c.isalnum() or c in (" ", "-", "_") else "" for c in topic)
        safe_topic = safe_topic.strip().replace(" ", "-")[:50]  # Limit length

        # Add timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        return f"research_{safe_topic}_{timestamp}.md"
